### PR TITLE
[feature] added OBJMetaProcess.processFile to count faces and vertexs

### PR DESCRIPTION
**Pull request by liujialesg**
Synchronous version added at api/models
Test folder added with a .obj file for testing and a test case

### CODE REVIEW

**Comment by liujialesg** [comment]
Test files and test case changed to use smaller test file

**Comment by imouto1994** [comment]
The `models` folder is for database models. Not for 3D models. This should be put in `helpers` folder. I will fix it for u

**Comment by liujialesg** [comment]
Added function for mtl file
Read comments for format of pathing

**Comment by imouto1994** [comment]
Can u check if test works correctly? It seems the build in Travis failed
https://travis-ci.org/nus-mtp/cubist/builds/108026617

**Comment by imouto1994** [comment]
Cool! Good to merge :+1:

**Pull request merged**
